# Generated by Django 5.0.4 on 2024-07-17 11:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("generator", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="featured_news",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("headline", models.CharField(max_length=200)),
                ("desc", ckeditor.fields.RichTextField()),
                ("date", models.DateField()),
                ("location", models.TextField()),
                ("writer", models.CharField(max_length=30)),
                ("image", models.ImageField(blank=True, upload_to="media")),
            ],
        ),
    ]
