# Generated by Django 5.0.4 on 2024-07-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("generator", "0002_featured_news"),
    ]

    operations = [
        migrations.CreateModel(
            name="helpsupport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=200)),
                ("message", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="myreview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=200)),
                ("message", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="featured_news",
        ),
    ]
